apiVersion: apps/v1
kind: Deployment
metadata:
  name: mikroserwis-b
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mikroserwis-b
  template:
    metadata:
      labels:
        app: mikroserwis-b
    spec:
      containers:
        - name: mikroserwis-b
          image: jnadolski223/mikroserwis-b:3.1
          ports:
            - containerPort: 3001
          env:
            - name: MONGO_USERNAME
              valueFrom:
                secretKeyRef:
                  name: database
                  key: mongo-root-username
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database
                  key: mongo-root-password
          resources:
            limits:
              memory: "1Gi"
              cpu: "1"
