apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
        - name: database
          image: mongo:latest
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: database
                  key: mongo-root-username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database
                  key: mongo-root-password
          volumeMounts:
            - mountPath: /data/db
              name: db-storage
          resources:
            limits:
              memory: "2Gi"
              cpu: "2"
      volumes:
        - name: db-storage
          persistentVolumeClaim:
            claimName: database
