apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database
spec:
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 1Gi
