apiVersion: apps/v1
kind: Deployment
metadata:
  name: mikroserwis-b
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mikroserwis-b
  template:
    metadata:
      labels:
        app: mikroserwis-b
    spec:
      containers:
        - name: mikroserwis-b
          image: jnadolski223/mikroserwis-b:2.0
          ports:
            - containerPort: 3001
