version: "3.8"

services:
  express-app:
    build: .
    ports:
      - "3000:3000"
    command: ["npm", "run", "start"]
    depends_on:
      - redis
  
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
