apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\kuban\AppData\Local\Microsoft\WinGet\Packages\Kubernetes.kompose_Microsoft.Winget.Source_8wekyb3d8bbwe\kompose.exe convert -f .\docker-compose-app.yml
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: app
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: app
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\kuban\AppData\Local\Microsoft\WinGet\Packages\Kubernetes.kompose_Microsoft.Winget.Source_8wekyb3d8bbwe\kompose.exe convert -f .\docker-compose-app.yml
        kompose.version: 1.36.0 (ae2a39403)
      labels:
        io.kompose.service: app
    spec:
      containers:
        - image: my-app
          name: app
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
